[project]
authors = ["jgallowa07 <jaredgalloway07@gmail.com>"]
channels = ["conda-forge", "bioconda"]
name = "mat-pcp"
platforms = ["osx-64", "linux-64"]
version = "0.1.0"

[tasks]

[dependencies]
bte = ">=0.9.0,<0.10"
pandas = ">=2.2.3,<3"

[pypi-dependencies]
