# Configuration file for pipeline

# List matutils pre-built mutation-annotated tree. We do the analysis for each tree and put
# in a subdirectory called `results_{mat}` where `{mat}` is the name of that tree.
# The most recent public trees are at
# http://hgdownload.soe.ucsc.edu/goldenPath/wuhCor1/UShER_SARS-CoV-2/
mat_trees:
  Feb-12-2025:
    mat: mat_trees/gisaidAndPublic.2025-02-12.masked.pb.gz 
    meta: mat_trees/gisaidAndPublic.2025-02-12.metadata.tsv.gz 

qc_filter_options:
  invalid_date_resolutions: ["MISSING", "MONTH", "YEAR"]
  min_date: "2019-12-01"
  valid_hosts: ["Human", "Homo sapiens"]
  missing_host_is_valid: True
  min_genome_length: 28000
  max_genome_length: 32000

# Reference GTF and FASTA, and location of spike coding sequence
ref_fasta: http://hgdownload.soe.ucsc.edu/goldenPath/wuhCor1/bigZips/wuhCor1.fa.gz
ref_gtf: http://hgdownload.soe.ucsc.edu/goldenPath/wuhCor1/bigZips/genes/ncbiGenes.gtf.gz

# additional kwargs to go with the matUtils extract command, post metadata filtering. 
mat_subset_kwargs: ""

# Added parameters for metadata filtering
subset_frac: 0.005  # Default to 5% random sampling

# Date cutoff for filtering metadata
datetime_cutoff: "2022-06-01"

# gene annotations to add to the reference GTF, which is missing ORF9b, see:
# https://github.com/jbloomlab/SARS2-mut-fitness/issues/21
add_to_ref_gtf:
  ORF9b: [28284, 28577]
